apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  namespace: default
#secrets:
#  - name: gitlab-secret
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: gitlab-secret
#  annotations:
#    kubernetes.io/service-account.name: gitlab
#type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-role
  namespace: default
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: gitlab-role-binding
roleRef:
  kind: Role
  name: gitlab-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: gitlab
    namespace: default