apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: httprelay-ip
spec:
  backend:
    serviceName: httprelay-deployment
    servicePort: 8800

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress-tls
  annotations:
    kubernetes.io/ingress.global-static-ip-name: httprelay-ip
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
spec:
  backend:
    serviceName: httprelay-deployment
    servicePort: 8800
  tls:
    - secretName: demo-httprelay-io-tls
      hosts:
        - demo.httprelay.io