apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jonas.jasas@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    http01: {}

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: demo.httprelay.io
  namespace: default
spec:
  secretName: demo-httprelay-io-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: demo.httprelay.io
  dnsNames:
  - demo.httprelay.io
  acme:
    config:
    - http01:
        ingress: letsencrypt-ingress
      domains:
      - demo.httprelay.io