apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-account

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deployer
rules:
- apiGroups: ["extensions"] # "" indicates the core API group
  resources: ["image", "deployments"]
  verbs: ["set", "get"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-role-binding
  namespace: default
subjects:
- kind: User
  name: deployer-account
  apiGroup: extensions
roleRef:
  kind: Role
  name: deployer
  apiGroup: extensions

#---
#
#apiVersion: rbac.authorization.k8s.io/v1beta1
#kind: ClusterRoleBinding
#metadata:
#  name: panel-rbac
#subjects:
#  - kind: ServiceAccount
#    # Reference to upper's `metadata.name`
#    name: default
#    # Reference to upper's `metadata.namespace`
#    namespace: default
#roleRef:
#  kind: ClusterRole
#  name: cluster-admin
#  apiGroup: rbac.authorization.k8s.io