image: golang

before_script:
  - export NS_DIR=$GOPATH/src/gitlab.com/$CI_PROJECT_NAMESPACE
  - export PROJ_DIR=$NS_DIR/$CI_PROJECT_NAME
  - mkdir -p $NS_DIR
  - ln -s $CI_PROJECT_DIR $PROJ_DIR
  - cd $PROJ_DIR
  - go get ./...

stages:
  - test
  - build

test:
  stage: test
  script:
    - go build --race ./cmd/...
    - go test ./test/... -cover

build:
  stage: build

  artifacts:
    paths:
      - bin/

  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/$CI_PROJECT_NAME
    - GOOS=linux GOARCH=arm go build -o bin/$CI_PROJECT_NAME
    - GOOS=windows GOARCH=amd64 go build -o bin/$CI_PROJECT_NAME.exe
    - GOOS=darwin GOARCH=amd64 go build -o bin/$CI_PROJECT_NAME