.docker:
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375
    GITLAB_REG_TAG: registry.gitlab.com/$CI_PROJECT_PATH:$CI_PIPELINE_IID

build:docker:img:
  extends: .docker

  services:
    - docker:dind

  script:
    - docker build --tag $GITLAB_REG_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push $GITLAB_REG_TAG