#!/bin/bash
set -x

gcloud container clusters delete httprelay --quiet --zone=europe-west4 --project http-relay-1490338352158

# Create static IP in GCloud
#gcloud compute addresses create httprelay-ip --global
gcloud container clusters create httprelay --zone=europe-west4 --machine-type=g1-small --num-nodes=1 --cluster-version=1.14.6 --disk-size=10GB --project http-relay-1490338352158
gcloud beta container clusters get-credentials httprelay --region europe-west4 --project http-relay-1490338352158

kubectl create namespace cert-manager
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.11.0/cert-manager.yaml --validate=false
kubectl apply -f letsencrypt.yaml

sleep 10s
kubectl apply -f deployer-account.yaml
kubectl apply -f deployment.yaml
#kubectl expose deployment httprelay-deployment --target-port=8080 --type=NodePort
kubectl apply -f ingress.yaml


